; ------------ Credits ------------
; Creator: Fernando Daniel Jaime.
; Programmer Alias: FDJ-Dash.
; ------------ App Details ------------
; App Name: Game Controller Remap.
;--------------------------------------------------
; Description: This is an app aimed towards game controller devices not recognized by some games
; but still recognized by the Operating System.
;--------------------------------------------------
; HINT: If you delete this file or move it away from its folder,
; Game Controller Remap will generate a new file on the spot.
;--------------------------------------------------
; Listed colors:
; Black Silver Gray White Maroon Red Purple Fuchsia Green Lime Olive Yellow Navy Blue Teal Aqua
; If the color name you need is not listed you can still write its RGB value.
;--------------------------------------------------
[FontType]
MainFontType=Comic Sans MS
MessageAppNameFontType=Georgia
LicenseKeyFontType=Comic Sans MS
MessageMainMsgFontType=Georgia
MessageFontType=Georgia
;--------------------------------------------------
[FontColors]
MainFontColor=FF9933
MessageAppNameFontColor=FF9933
LicenseKeyFontColor=70A0FA
MessageMainMsgFontColor=FF9933
MessageFontColor=FF9933
;--------------------------------------------------
[Background]
BackgroundColor=2F2F2F
BackgroundPicture=
MessageBackgroundPicture=
;--------------------------------------------------
[Properties]
ExitMessageTimeWait=3000
GuiPriorityAlwaysOnTop=1
ControllerLoopInterval=100
;----------
CtrlRemapYesNo=1
;----------
NormalMode=1
RaceMode=0
;----------
CursorMovement=1
RotateCamera=0
RotateCameraCtrldown=0
RotateCameraShiftdown=0
;----------
PositionX=1179
PositionY=181
;----------
ExitGameControllerRemap=|
;--------------------------------------------------
[Settings]
CheckforUpdatesDaily=1
CheckforupdatesWeekly=0
NeverCheckForUpdates=0
NeedUpdate=1
LastUpdateCheckTimeStamp=20260313184832
;--------------------------------------------------
[ControllerCursorMovement]
CursorSensRight=10
CursorSensDown=10
CursorSensLeft=-10
CursorSensUp=-10
CursorSpeed=0
;--------------------------------------------------
[ControllerCameraRotation]
ShiftDownRotation=Shift
CtrlDownRotation=Ctrl
RotateLeft=Left
RotateRight=Right
RotateUp=Up
RotateDown=Down
;--------------------------------------------------
[ControllerNormalModeRemap]
ButtonA=Space
ButtonB=RButton
ButtonX=esc
ButtonY=f
SprintLB=Shift
ScannerRB=n
ButtonRT=w
ButtonLT=s
ButtonStart=tab
ButtonBack=i
;--------------------------------------------------
[ControllerAxisRemap]
TurnLeft=a
TurnRight=d
MoveForward=w
MoveBackward=s
LeftPOV=a
RightPOV=d
ForwadPOV=w
BackwardPOV=s
;--------------------------------------------------
[ControllerRaceModeRemap]
AfterBurnerButtonA=Shift
ButtonLB=a
ButtonRB=d
RespawnY=r
AcelerateButtonRT=w
ReverseButtonLT=s
