; ------------ Credits ------------
; Creator: Fernando Daniel Jaime.
; Programmer Alias: FDJ-Dash.
; Gamer Alias: Mean Little, Grey Dash, Dash.
; ------------ App Details ------------
; App Full Name: Mean Little's Game Controller Remap.
; Description: This is an app aimed towards game controller devices not recognized by some games
; but still recognized by the Operating System.
;--------------------------------------------------
; HINT: If you delete this file or move it away from its forder,
; Game Controller Remap will generate a new file on the spot.
;--------------------------------------------------
; Find the list of key names here: https://www.autohotkey.com/docs/v2/KeyList.htm 
;-------------------------------
; See the list of recommended fonts here: https://www.autohotkey.com/docs/v2/misc/FontsStandard.htm
;-------------------------------
; See the list of color names and RGB values here: https://www.autohotkey.com/docs/v2/misc/Colors.htm
; Black Silver Gray White Maroon Red Purple Fuchsia Green Lime Olive Yellow Navy Blue Teal Aqua
; If the color name you need is not listed you can still write its RGB value
;--------------------------------------------------
[Properties]
ExitMessageTimeWait=3000
GuiPriorityAlwaysOnTop=1
ControllerLoopInterval=100
;-------------------------------
PositionX=1433
PositionY=108
;-------------------------------
ExitGameControllerRemap=Esc
;--------------------------------------------------
[Settings]
CheckforUpdatesDaily=1
CheckforupdatesWeekly=0
NeverCheckForUpdates=0
NeedUpdate=1
;-------------------------------
LastUpdateCheckTimeStamp=20250127170401
;--------------------------------------------------
[ControllerCursorMovement]
CursorSensRight=100
CursorSensDown=100
CursorSensLeft=-100
CursorSensUp=-100
CursorSpeed=0
;--------------------------------------------------
[ControllerCameraRotation]
ShiftDownRotation=Shift
CtrlDownRotation=Ctrl
RotateLeft=Left
RotateRight=Right
RotateUp=Up
RotateDown=Down
;--------------------------------------------------
[ControllerNormalModeRemap]
ButtonA=Space
ButtonB=RButton
ButtonX=esc
ButtonY=f
SprintLB=Shift
ScannerRB=n
ButtonRT=w
ButtonLT=s
ButtonStart=tab
ButtonBack=i
;--------------------------------------------------
[ControllerAxisRemap]
TurnLeft=a
TurnRight=d
MoveForward=w
MoveBackward=s
LeftPOV=a
RightPOV=d
ForwadPOV=w
BackwardPOV=s
;--------------------------------------------------
[ControllerRaceModeRemap]
AfterBurnerButtonA=Shift
ButtonLB=a
ButtonRB=d
RespawnY=r
AcelerateButtonRT=w
ReverseButtonLT=s
;--------------------------------------------------
[FontType]
MainFontType=Comic Sans MS
MessageAppNameFontType=Georgia
LicenseKeyFontType=Comic Sans MS
MessageMainMsgFontType=Georgia
MessageFontType=Georgia
;--------------------------------------------------
[FontColors]
MainFontColor=FF9933
MessageAppNameFontColor=FF9933
LicenseKeyFontColor=70A0FA
MessageMainMsgFontColor=FF9933
MessageFontColor=FF9933
;--------------------------------------------------
[Background]
BackgroundColor=2F2F2F
BackgroundPicture=
MessageBackgroundPicture=
