;--------------------------------------------------
; HINT: If you delete this file or move it away from its forder,
; Game Controller Remap will generate a new file on the spot.
;--------------------------------------------------
; WARNING: Don't set this file as read only!
;--------------------------------------------------
[Properties]
ExitMessageTimeWait=3000
SuspendHotkeys=0
;--------------------------------------------------
[Controller]
ControllerLoop=100
;--------------------------------------------------
[ControllerCursorMovement]
CursorSensRight=100
CursorSensDown=100
CursorSensLeft=-100
CursorSensUp=-100
CursorSpeed=0
;--------------------------------------------------
[ControllerCameraRotation]
ShiftDownRotation=Shift
CtrlDownRotation=Ctrl
RotateLeft=Left
RotateRight=Right
RotateUp=Up
RotateDown=Down
;--------------------------------------------------
[ControllerNormalModeRemap]
ButtonA=Space
ButtonB=RButton
ButtonX=esc
ButtonY=f
SprintLB=Shift
ScannerRB=n
ButtonRT=w
ButtonLT=s
ButtonStart=tab
ButtonBack=i
;--------------------------------------------------
[ControllerAxisRemap]
TurnLeft=a
TurnRight=d
MoveForward=w
MoveBackward=s
LeftPOV=a
RightPOV=d
ForwadPOV=w
BackwardPOV=s
;--------------------------------------------------
[ControllerRaceModeRemap]
AfterBurnerButtonA=Shift
ButtonLB=a
ButtonRB=d
RespawnY=r
AcelerateButtonRT=w
ReverseButtonLT=s
